src/apps/alterprice/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from alterprice import views


urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),

    # APPs
    url(r'^markup/', include('markup.urls', namespace="markup")),
    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^catalog/', include('catalog.urls', namespace="catalog")),
    url(r'^client/', include('client.urls', namespace="client")),


    # API urls
    url(r'^api/product/', include('product.api.urls', namespace="product-api")),
    url(r'^api/catalog/', include('catalog.api.urls', namespace="catalog-api")),
    url(r'^api/brand/', include('brand.api.urls', namespace="brand-api")),
    url(r'^api/shop/', include('shop.api.urls', namespace="shop-api")),
    url(r'^api/user/', include('apuser.api.urls', namespace="user-api")),
    url(r'^api/client/', include('client.api.urls', namespace="client-api")),

    # Aadmin urls
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/apps/client/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from client.api import views

urlpatterns = patterns(
    '',
    url(r'^signin/$', views.SignInAPIView.as_view(), name='signin'),
    url(r'^signin/welcome/$', views.SignInAPIView.as_view(), name='signin_welcome'),
    url(r'^signup/$', views.SignUpAPIView.as_view(), name='signup'),
    url(r'^profile/$', views.Profile.as_view(), name='profile'),
    url(r'^profile/password/$', views.ProfilePassword.as_view(), name='profile-password'),
    url(r'^recovery/$', views.Recovery.as_view(), name='recovery'),
    url(r'^recovery/password/$', views.RecoveryPassword.as_view(), name='recovery-password'),
    url(r'^email/update/$', views.UpdateEmail.as_view(), name='email-update'),
    url(r'^invoice/add/$', views.InvoiceCreateView.as_view(), name='invoice-add'),
    url(r'^invoice/list/$', views.InvoiceListView.as_view(), name='invoice-list'),
    url(r'^robokassa/add/$', views.RobokassaCreatePaymentAPIView.as_view(), name='robokassa-add'),
    url(r'^robokassa/result/$', views.RobokassaResultAPIView.as_view(), name='robokassa-result'),
    url(r'^market/offer/$', views.RobokassaResultAPIView.as_view(), name='robokassa-result'),
)

src/apps/client/urls.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, url
from client import views


urlpatterns = patterns(
    '',
    url(r'^$', views.ClientIndexPageView.as_view(), name='index'),
    url(r'^agreements/$', views.ClientAgreementsPageView.as_view(), name='agreements'),
    url(r'^contacts/$', views.ClientContactsPageView.as_view(), name='contacts'),
    # auth urls
    url(r'^login/$', views.ClientSignInPageView.as_view(), name='login'),
    url(r'^signout/$',
        'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('client:index'), },
        name='signout'),
    url(r'^registration/$', views.ClientSignUpPageView.as_view(), name='registration'),
    url(r'^password_reset/$', views.ClientPasswordResetPageView.as_view(), name='password_reset'),

    url(r'^activate/(?P<token>%s)/$' % settings.EMAIL_TOKEN_PATTERN,
        views.ActivateView.as_view(),
        name='activate-link'),
    url(r'^password/(?P<token>%s)/$' % settings.RECOVERY_TOKEN_PATTERN,
        views.RecoveryPassword.as_view(),
        name="recovery-link"),

    # cabinet urls
    url(r'^profile/$', views.ClientProfilePageView.as_view(), name='profile'),
    url(r'^shop/add/$', views.ClientShopAddPageView.as_view(), name='shop_add'),
    url(r'^shop/(?P<pk>\d+)/$', views.ClientShopDetailPageView.as_view(), name='shop_detail'),
    url(r'^wallet/balance/$', views.ClientWalletBalancePageView.as_view(), name='wallet_balance'),
    url(r'^wallet/refill/$', views.ClientWalletRefillPageView.as_view(), name='wallet_refill'),

    url(r'^statistics/shop/(?P<pk>\d+)/$',
        views.ClientStatisticShopView.as_view(),
        name='statistics_shop'),

    url(r'^statistics/pricelist/(?P<pk>\d+)/$',
        views.ClientStatisticPricelistView.as_view(),
        name='statistics_pricelist'
    ),

    url(r'^pricelist/(?P<pk>\d+)/$', views.ClientPricelistDetailPageView.as_view(), name='pricelist_detail'),
    url(r'^pricelist/add/$', views.ClientPricelistAddPageView.as_view(), name='pricelist_add'),
    url(r'^invoice/download/(?P<pk>\d+)/$', views.download_invoice, name='invoice_download'),

    # Middleware UL
    url(r'^shop/change/$', views.ChnageShop.as_view(), name='change-shop'),
)

src/apps/client/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
# PRoject imports
from shop.models.shop import Shop


class ChangeShopForm(forms.Form):
    shop = forms.ModelChoiceField(
        empty_label=_('Выберете магазин'),
        queryset=Shop.objects.all())

src/apps/client/api/views.py
import logging
from hashlib import md5
from urllib.request import urlopen
from math import ceil

from rest_framework import permissions
from rest_framework import status
from rest_framework.renderers import StaticHTMLRenderer
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView, UpdateAPIView, ListCreateAPIView, \
    ListAPIView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth import login as auth_login
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.hashers import make_password
from django.core.urlresolvers import resolve

from apuser.models import BalanceHistory
from apuser.models.payment import InvoiceRequest, Payment
from apuser import models
from apuser.models.profile import EmailDelivery, OperatorProfile
from catalog.models.token import PasswordRecovery
from client.api import serializers
from django.conf import settings
from utils.views import APIView
from django.contrib.auth import update_session_auth_hash


logger = logging.getLogger(__name__)


class SignInAPIView(APIView):
    serializer_class = serializers.SignInSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        auth_login(request, serializer.object)

    def success_data(self, serializer):
        response = {}

        if resolve(self.request.path_info).url_name is 'signin_welcome':
            response['redirect_to'] = reverse_lazy('client:shop_add')
        else:
            response['redirect_to'] = reverse_lazy('client:profile')

        return response


class SignUpAPIView(CreateAPIView):
    serializer_class = serializers.SignUpSerializer
    permission_classes = (
        permissions.AllowAny,
    )

    def perform_create(self, serializer):
        user = serializer.save()
        return user

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        response = {}
        if serializer.is_valid():
            user = self.perform_create(serializer)
            headers = self.get_success_headers(serializer.data)
            response['status'] = 'success'
            response['message'] = _('Для завершения регистрации перейдите по ссылке из письма отправленного на ваш e-mail. Если не найдете во входящих, проверьте "спам"')
            EmailDelivery.objects.make(
                template='client/register.html',
                email=serializer.validated_data.get('email'),
                context={
                    'link': reverse('client:activate-link',
                                    kwargs={'token': user.emailvalidation_set.all()[0].token}),
                    'domain': settings.DEFAULT_HOST
                }

            )
            if user.client_profile.operator:
                operator_email = user.client_profile.operator.user.email
            else:
                emails = [x.user.email for x in OperatorProfile.objects.all()]
                operator_email = ','.join(emails)
            EmailDelivery.objects.make(
                template='operator/register.html',
                email=operator_email
            )
            return Response(response, status=status.HTTP_201_CREATED, headers=headers)
        else:
            response['status'] = 'fail'
            response['errors'] = serializer.errors
            headers = self.get_success_headers(serializer.data)
            return Response(response,
                            status=status.HTTP_400_BAD_REQUEST,
                            headers=headers)


class Recovery(APIView):
    serializer_class = serializers.RecoverySerializer
    permission_classes = (
        permissions.AllowAny,
    )

    def success_action(self, request, serializer):
        email = serializer.validated_data.get('email')
        user = models.AlterPriceUser.objects.get(email=email)
        r = PasswordRecovery.objects.make(user=user)
        EmailDelivery.objects.make(
            template='client/activate.html',
            email=user.email,
            context={'token': r.token}
        )

    def success_data(self, serializer):
        response = {}
        # email = serializer.validated_data.get('email')
        response['message'] = _(
            'Выслано сообщение со ссылкой на восстановление')
        return response


class RecoveryPassword(APIView):
    serializer_class = serializers.RecoveryPasswordSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        password = serializer.validated_data.get('password')
        pr = PasswordRecovery.objects.get_valid(
            token=serializer.validated_data.get('token'))
        pr.recover()
        user = pr.user
        user.set_password(password)
        user.save()

    def success_data(self, serializers):
        response = {}
        response['message'] = _('Ваш пароль был успешно изменен.')
        response['redirect_to'] = reverse('client:login')
        return response


class UpdateEmail(APIView):
    serializer_class = serializers.UpdateEmailSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        self.request.user.email = serializer.validated_data.get('new_email')
        self.request.user.save()

    def success_data(self, serializers):
        response = {}
        response['message'] = _('Ваш email был успешно изменен.')
        response['status'] = 'success'
        return response


class InvoiceListView(ListAPIView):
    model = InvoiceRequest
    serializer_class = serializers.InvoiceRequestListSerializer
    permission_classes = (permissions.IsAuthenticated, )

    def get_queryset(self):
        queryset = self.model.objects.filter(client=self.request.user.client_profile)
        return queryset


class InvoiceCreateView(CreateAPIView):
    serializer_class = serializers.InvoiceRequestAddSerializer
    permission_classes = (permissions.IsAuthenticated, )
    model = InvoiceRequest

    def get_queryset(self):
        return self.model.objects.filter(client=self.request.user.client_profile)

    def perform_create(self, serializer):
        ir = serializer.save()
        ir.client = self.request.user.client_profile
        ir.save()

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        response = {}
        if serializer.is_valid():
            self.perform_create(serializer)
            headers = self.get_success_headers(serializer.data)
            response['status'] = 'success'
            response['message'] = _('Запрос на счет отправлен.')
            return Response(response, status=status.HTTP_201_CREATED, headers=headers)
        else:
            response['status'] = 'fail'
            response['errors'] = serializer.errors
            headers = self.get_success_headers(serializer.data)
            return Response(response,
                            status=status.HTTP_400_BAD_REQUEST,
                            headers=headers)


class Profile(APIView):
    serializer_class = serializers.ProfileSerializer

    def success_action(self, request, serializer):
        phone = serializer.validated_data.get('phone')
        request.user.client_profile.phone = phone
        request.user.client_profile.save()

    def success_data(self, serializers):
        response = {}
        response['status'] = 'success'
        return response


class ProfilePassword(APIView):
    serializer_class = serializers.ProfilePasswordSerializer

    def success_action(self, request, serializer):
        password = serializer.validated_data.get('password')
        request.user.set_password(password)
        request.user.save()
        update_session_auth_hash(request, request.user)

    def success_data(self, serializers):
        response = {}
        response['status'] = 'success'
        response['message'] = _('Ваш пароль успешно изменен')
        return response


class RobokassaResultAPIView(APIView):
    serializer_class = serializers.RobokassaResultSerializer
    renderer_classes = (StaticHTMLRenderer, )

    def post(self, request, *args, **kwargs):
        data = self.prepare_data(request)
        serializer = self.serializer_class(data=data, context=dict(request=request))
        response = ''
        if serializer.is_valid():
            payment_id = serializer.validated_data.get('InvId')
            payment = Payment.objects.get(id=payment_id)
            payment.robokassa_success = True
            payment.save()
            BalanceHistory.objects.increase(
                balance=payment.client.balance,
                payment=payment,
            )
            EmailDelivery.objects.make(
                template='client/payment_success.html',
                email=payment.client.user.email,
                context={'amount': payment.amount}
            )
            if payment.client.operator:
                EmailDelivery.objects.make(
                    template='client/payment_success.html',
                    email=payment.client.operator.user.email,
                    context={'amount': payment.amount}
                )
            self.success_action(request, serializer)
            response = 'OK%d' % payment_id
        return Response(response, status=200)


class RobokassaCreatePaymentAPIView(CreateAPIView):
    model = Payment
    permission_classes = (permissions.IsAuthenticated, )
    serializer_class = serializers.RobokassaCreateSerializer

    def perform_create(self, serializer):
        # payment = serializer.save()
        payment = self.model(
            client=self.request.user.client_profile,
            amount=serializer.validated_data.get('OutSum'),
            payment_type=Payment.ONLINE,
            payment_detail=Payment.PAYMENT,
        )
        payment.save()
        return payment

src/templates/apps/client/wallet/balance.html
{% extends 'client_base.html' %}

{% load humanize %}

{% block content%}
    <div id="payments-page">
        <div class="h1">Оплаты</div>
        <div class="pure-g">
            <div class="pure-u-1-2">
                <div class="block-1-x user-balance-informer">
                    <span>Текущий баланс</span>
                    <div><span>{{ user.client_profile.balance.value|intcomma|default:0 }}</span> руб.</div>
                    <a class="refill-link" href="{% url 'client:wallet_refill' %}">Перейти к пополнению</a>
                </div>
            </div>
        </div>
        <div class="pure-g">
            <div class="pure-u-1-2">
                <div class="block-2-x payment-block">
                    <header>Поступление</header>
                    <div id="client-wallet-payments-layout"></div>
                    <footer class="client-wallet-payments-pager"></footer>
                </div>
            </div>
            <div class="pure-u-1-2 text-right">
                <div class="block-2-x payment-block">
                    <header>Выставленные счета</header>
                    <div id="client-wallet-bills-layout"></div>
                    <footer class="client-wallet-bills-pager"></footer>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/apps/client/wallet/refill.html
{% extends 'client_base.html' %}

{% block content%}
    <div id="payments-refill-page">
        <div class="h1">Пополнения</div>
        <div id="client-wallet-refill-view">
            <ul class="tabs-nav">
                <li class="active"><a href="#" class="tab-link" data-tab="online">Онлайн-оплата</a></li>
                <li><a href="#" class="tab-link" data-tab="card">Оплата по банковскому счету</a></li>
            </ul>
        </div>
        <div id="client-wallet-refill-online-form-view">
            <div class="block-ful-x tab-content online active">
                <form action="{% url 'client-api:robokassa-add' %}" method="post" id="client-wallet-refill-online-form" class="online-refill" data-tab="online">
                    <div class="pure-g">
                        <div class="pure-u-1-2 left-column">
                            <label class="quantum-label field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">Введите сумму</div>
                                <div class="pure-u-1-1 field-value">
                                    <input id="quantum-input" name="OutSum" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                        </div>
                    </div>
                    <div class="pure-g">
                        <div class="pure-u-1-2 form-footer">
                            <button type="submit" class="btn btn-purple">Продолжить</button>
                        </div>
                    </div>
                </form>
                <form id="robokassa-form" action="https://auth.robokassa.ru/Merchant/Index.aspx">
                    <input type="hidden" name="MerchantLogin" value="alterprice" />
                    <input id="robokassa-summ" type="hidden" name="OutSum" value="" />
                    <input id="robokassa-invid" type="hidden" name="InvId" value="" />
                    <input id="robokassa-signature" type="hidden" name="SignatureValue" value="" />
                    {% if is_test_pay %}
                    <input type="hidden" name="IsTest" value="1" />
                    {% endif %}
                </form>
            </div>
        </div>
        <div id="client-wallet-refill-card-form-view">
            <div class="block-ful-x tab-content card">
                <form action="{% url 'client-api:invoice-add' %}" method="post" id="client-wallet-refill-card-form" class="form-block" data-tab="online">
                    <div class="pure-g">
                        <div class="pure-u-1-2 left-column">
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">НАЗВАНИЕ ОРГАНИЗАЦИИ</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="company_name" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">ИНН</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="inn" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">КПП</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="kpp" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">БИК</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="bik" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">Р/С</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="rs" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">КОРРЕСПОНДЕНТСКИЙ СЧЕТ</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="ks" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                        </div>
                        <div class="pure-u-1-2 right-column">
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">НАЗВАНИЕ БАНКА</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="bank_name" type="text" class="b_input_text phone-mask" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">ФИО КОНТАКТНОГО ЛИЦА</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="fio" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">ТЕЛЕФОН КОНТАКТНОГО ЛИЦА</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="phone" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">ЮРИДИЧЕСКИЙ АДРЕС</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="legal_address" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <label class="pure-g field-wrapper vertical-field">
                                <div class="pure-u-1-1 field-name">ПОЧТОВЫЙ АДРЕС</div>
                                <div class="pure-u-1-1 field-value">
                                    <input name="post_address" type="text" class="b_input_text" value="">
                                </div>
                            </label>
                            <div class="form-footer">
                                <button type="submit" class="btn btn-purple">ЗАПРОСИТЬ СЧЁТ</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}