src/apps/alterprice/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from alterprice import views


urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),

    # APPs
    url(r'^markup/', include('markup.urls', namespace="markup")),
    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^catalog/', include('catalog.urls', namespace="catalog")),
    url(r'^client/', include('client.urls', namespace="client")),


    # API urls
    url(r'^api/product/', include('product.api.urls', namespace="product-api")),
    url(r'^api/catalog/', include('catalog.api.urls', namespace="catalog-api")),
    url(r'^api/brand/', include('brand.api.urls', namespace="brand-api")),
    url(r'^api/shop/', include('shop.api.urls', namespace="shop-api")),
    url(r'^api/user/', include('apuser.api.urls', namespace="user-api")),
    url(r'^api/client/', include('client.api.urls', namespace="client-api")),

    # Aadmin urls
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/apps/client/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from client.api import views

urlpatterns = patterns(
    '',
    url(r'^signin/$', views.SignInAPIView.as_view(), name='signin'),
    url(r'^signin/welcome/$', views.SignInAPIView.as_view(), name='signin_welcome'),
    url(r'^signup/$', views.SignUpAPIView.as_view(), name='signup'),
    url(r'^profile/$', views.Profile.as_view(), name='profile'),
    url(r'^profile/password/$', views.ProfilePassword.as_view(), name='profile-password'),
    url(r'^recovery/$', views.Recovery.as_view(), name='recovery'),
    url(r'^recovery/password/$', views.RecoveryPassword.as_view(), name='recovery-password'),
    url(r'^email/update/$', views.UpdateEmail.as_view(), name='email-update'),
    url(r'^invoice/add/$', views.InvoiceCreateView.as_view(), name='invoice-add'),
    url(r'^invoice/list/$', views.InvoiceListView.as_view(), name='invoice-list'),
    url(r'^robokassa/add/$', views.RobokassaCreatePaymentAPIView.as_view(), name='robokassa-add'),
    url(r'^robokassa/result/$', views.RobokassaResultAPIView.as_view(), name='robokassa-result'),
    url(r'^market/offer/$', views.RobokassaResultAPIView.as_view(), name='robokassa-result'),
)

src/apps/client/urls.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, url
from client import views


urlpatterns = patterns(
    '',
    url(r'^$', views.ClientIndexPageView.as_view(), name='index'),
    url(r'^agreements/$', views.ClientAgreementsPageView.as_view(), name='agreements'),
    url(r'^contacts/$', views.ClientContactsPageView.as_view(), name='contacts'),
    # auth urls
    url(r'^login/$', views.ClientSignInPageView.as_view(), name='login'),
    url(r'^signout/$',
        'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('client:index'), },
        name='signout'),
    url(r'^registration/$', views.ClientSignUpPageView.as_view(), name='registration'),
    url(r'^password_reset/$', views.ClientPasswordResetPageView.as_view(), name='password_reset'),

    url(r'^activate/(?P<token>%s)/$' % settings.EMAIL_TOKEN_PATTERN,
        views.ActivateView.as_view(),
        name='activate-link'),
    url(r'^password/(?P<token>%s)/$' % settings.RECOVERY_TOKEN_PATTERN,
        views.RecoveryPassword.as_view(),
        name="recovery-link"),

    # cabinet urls
    url(r'^profile/$', views.ClientProfilePageView.as_view(), name='profile'),
    url(r'^shop/add/$', views.ClientShopAddPageView.as_view(), name='shop_add'),
    url(r'^shop/(?P<pk>\d+)/$', views.ClientShopDetailPageView.as_view(), name='shop_detail'),
    url(r'^wallet/balance/$', views.ClientWalletBalancePageView.as_view(), name='wallet_balance'),
    url(r'^wallet/refill/$', views.ClientWalletRefillPageView.as_view(), name='wallet_refill'),

    url(r'^statistics/shop/(?P<pk>\d+)/$',
        views.ClientStatisticShopView.as_view(),
        name='statistics_shop'),

    url(r'^statistics/pricelist/(?P<pk>\d+)/$',
        views.ClientStatisticPricelistView.as_view(),
        name='statistics_pricelist'
    ),

    url(r'^pricelist/(?P<pk>\d+)/$', views.ClientPricelistDetailPageView.as_view(), name='pricelist_detail'),
    url(r'^pricelist/add/$', views.ClientPricelistAddPageView.as_view(), name='pricelist_add'),
    url(r'^invoice/download/(?P<pk>\d+)/$', views.download_invoice, name='invoice_download'),

    # Middleware UL
    url(r'^shop/change/$', views.ChnageShop.as_view(), name='change-shop'),
)

src/apps/shop/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from shop.api import views

urlpatterns = patterns(
    '',
    url(r'^create/$', views.ShopCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/update$', views.ShopUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/yml/add/$', views.AddYML.as_view(), name='add-yml'),
    url(r'^list/client/$', views.ShopClientList.as_view(), name='client-list'),

    url(r'^yml/(?P<pk>\d+)/publish/$', views.YMLPublish.as_view(), name='yml-publish'),
    url(r'^yml/(?P<pk>\d+)/unpublish/$', views.YMLUnPublish.as_view(), name='yml-unpulish'),
    url(r'^yml/(?P<pk>\d+)/update/$', views.YMLUpdate.as_view(), name='yml-update'),
    url(r'^yml/(?P<pk>\d+)/delete/$', views.YMLDelete.as_view(), name='yml-delete'),
    url(r'^yml/(?P<pk>\d+)/category/list/$', views.YMLCategoryList.as_view(), name='yml-category-list'),
    url(r'^yml/(?P<pk>\d+)/product/list/$', views.YMLProductList.as_view(), name='yml-product-list'),
    url(r'^yml/(?P<pk>\d+)/info/$', views.YMLInfo.as_view(), name='yml-info'),
    url(r'^category/(?P<pk>\d+)/update/$', views.YMLCategoryUpdate.as_view(), name='yml-category-update'),
    url(r'^statistic/offers/$', views.StatisticOffers.as_view(), name='statistic-offers'),
    url(r'^statistic/categories/$', views.StatisticCategories.as_view(), name='statistic-categories'),

)

src/apps/client/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
# PRoject imports
from shop.models.shop import Shop


class ChangeShopForm(forms.Form):
    shop = forms.ModelChoiceField(
        empty_label=_('Выберете магазин'),
        queryset=Shop.objects.all())

src/apps/client/api/views.py
import logging
from hashlib import md5
from urllib.request import urlopen
from math import ceil

from rest_framework import permissions
from rest_framework import status
from rest_framework.renderers import StaticHTMLRenderer
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView, UpdateAPIView, ListCreateAPIView, \
    ListAPIView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth import login as auth_login
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.hashers import make_password
from django.core.urlresolvers import resolve

from apuser.models import BalanceHistory
from apuser.models.payment import InvoiceRequest, Payment
from apuser import models
from apuser.models.profile import EmailDelivery, OperatorProfile
from catalog.models.token import PasswordRecovery
from client.api import serializers
from django.conf import settings
from utils.views import APIView
from django.contrib.auth import update_session_auth_hash


logger = logging.getLogger(__name__)


class SignInAPIView(APIView):
    serializer_class = serializers.SignInSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        auth_login(request, serializer.object)

    def success_data(self, serializer):
        response = {}

        if resolve(self.request.path_info).url_name is 'signin_welcome':
            response['redirect_to'] = reverse_lazy('client:shop_add')
        else:
            response['redirect_to'] = reverse_lazy('client:profile')

        return response


class SignUpAPIView(CreateAPIView):
    serializer_class = serializers.SignUpSerializer
    permission_classes = (
        permissions.AllowAny,
    )

    def perform_create(self, serializer):
        user = serializer.save()
        return user

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        response = {}
        if serializer.is_valid():
            user = self.perform_create(serializer)
            headers = self.get_success_headers(serializer.data)
            response['status'] = 'success'
            response['message'] = _('Для завершения регистрации перейдите по ссылке из письма отправленного на ваш e-mail. Если не найдете во входящих, проверьте "спам"')
            EmailDelivery.objects.make(
                template='client/register.html',
                email=serializer.validated_data.get('email'),
                context={
                    'link': reverse('client:activate-link',
                                    kwargs={'token': user.emailvalidation_set.all()[0].token}),
                    'domain': settings.DEFAULT_HOST
                }

            )
            if user.client_profile.operator:
                operator_email = user.client_profile.operator.user.email
            else:
                emails = [x.user.email for x in OperatorProfile.objects.all()]
                operator_email = ','.join(emails)
            EmailDelivery.objects.make(
                template='operator/register.html',
                email=operator_email
            )
            return Response(response, status=status.HTTP_201_CREATED, headers=headers)
        else:
            response['status'] = 'fail'
            response['errors'] = serializer.errors
            headers = self.get_success_headers(serializer.data)
            return Response(response,
                            status=status.HTTP_400_BAD_REQUEST,
                            headers=headers)


class Recovery(APIView):
    serializer_class = serializers.RecoverySerializer
    permission_classes = (
        permissions.AllowAny,
    )

    def success_action(self, request, serializer):
        email = serializer.validated_data.get('email')
        user = models.AlterPriceUser.objects.get(email=email)
        r = PasswordRecovery.objects.make(user=user)
        EmailDelivery.objects.make(
            template='client/activate.html',
            email=user.email,
            context={'token': r.token}
        )

    def success_data(self, serializer):
        response = {}
        # email = serializer.validated_data.get('email')
        response['message'] = _(
            'Выслано сообщение со ссылкой на восстановление')
        return response


class RecoveryPassword(APIView):
    serializer_class = serializers.RecoveryPasswordSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        password = serializer.validated_data.get('password')
        pr = PasswordRecovery.objects.get_valid(
            token=serializer.validated_data.get('token'))
        pr.recover()
        user = pr.user
        user.set_password(password)
        user.save()

    def success_data(self, serializers):
        response = {}
        response['message'] = _('Ваш пароль был успешно изменен.')
        response['redirect_to'] = reverse('client:login')
        return response


class UpdateEmail(APIView):
    serializer_class = serializers.UpdateEmailSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        self.request.user.email = serializer.validated_data.get('new_email')
        self.request.user.save()

    def success_data(self, serializers):
        response = {}
        response['message'] = _('Ваш email был успешно изменен.')
        response['status'] = 'success'
        return response


class InvoiceListView(ListAPIView):
    model = InvoiceRequest
    serializer_class = serializers.InvoiceRequestListSerializer
    permission_classes = (permissions.IsAuthenticated, )

    def get_queryset(self):
        queryset = self.model.objects.filter(client=self.request.user.client_profile)
        return queryset


class InvoiceCreateView(CreateAPIView):
    serializer_class = serializers.InvoiceRequestAddSerializer
    permission_classes = (permissions.IsAuthenticated, )
    model = InvoiceRequest

    def get_queryset(self):
        return self.model.objects.filter(client=self.request.user.client_profile)

    def perform_create(self, serializer):
        ir = serializer.save()
        ir.client = self.request.user.client_profile
        ir.save()

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        response = {}
        if serializer.is_valid():
            self.perform_create(serializer)
            headers = self.get_success_headers(serializer.data)
            response['status'] = 'success'
            response['message'] = _('Запрос на счет отправлен.')
            return Response(response, status=status.HTTP_201_CREATED, headers=headers)
        else:
            response['status'] = 'fail'
            response['errors'] = serializer.errors
            headers = self.get_success_headers(serializer.data)
            return Response(response,
                            status=status.HTTP_400_BAD_REQUEST,
                            headers=headers)


class Profile(APIView):
    serializer_class = serializers.ProfileSerializer

    def success_action(self, request, serializer):
        phone = serializer.validated_data.get('phone')
        request.user.client_profile.phone = phone
        request.user.client_profile.save()

    def success_data(self, serializers):
        response = {}
        response['status'] = 'success'
        return response


class ProfilePassword(APIView):
    serializer_class = serializers.ProfilePasswordSerializer

    def success_action(self, request, serializer):
        password = serializer.validated_data.get('password')
        request.user.set_password(password)
        request.user.save()
        update_session_auth_hash(request, request.user)

    def success_data(self, serializers):
        response = {}
        response['status'] = 'success'
        response['message'] = _('Ваш пароль успешно изменен')
        return response


class RobokassaResultAPIView(APIView):
    serializer_class = serializers.RobokassaResultSerializer
    renderer_classes = (StaticHTMLRenderer, )

    def post(self, request, *args, **kwargs):
        data = self.prepare_data(request)
        serializer = self.serializer_class(data=data, context=dict(request=request))
        response = ''
        if serializer.is_valid():
            payment_id = serializer.validated_data.get('InvId')
            payment = Payment.objects.get(id=payment_id)
            payment.robokassa_success = True
            payment.save()
            BalanceHistory.objects.increase(
                balance=payment.client.balance,
                payment=payment,
            )
            EmailDelivery.objects.make(
                template='client/payment_success.html',
                email=payment.client.user.email,
                context={'amount': payment.amount}
            )
            if payment.client.operator:
                EmailDelivery.objects.make(
                    template='client/payment_success.html',
                    email=payment.client.operator.user.email,
                    context={'amount': payment.amount}
                )
            self.success_action(request, serializer)
            response = 'OK%d' % payment_id
        return Response(response, status=200)


class RobokassaCreatePaymentAPIView(CreateAPIView):
    model = Payment
    permission_classes = (permissions.IsAuthenticated, )
    serializer_class = serializers.RobokassaCreateSerializer

    def perform_create(self, serializer):
        # payment = serializer.save()
        payment = self.model(
            client=self.request.user.client_profile,
            amount=serializer.validated_data.get('OutSum'),
            payment_type=Payment.ONLINE,
            payment_detail=Payment.PAYMENT,
        )
        payment.save()
        return payment

src/templates/apps/client/pricelist/add.html
{% extends 'client_base.html' %}

{% block content%}
    <div id="client-pricelist-detail">
        <div class="h1">Добавление прайс-листа</div>
        <div class="pure-g">
            <div class="pure-u-3-4">
                <div id="client-pricelist-detail-params-form-vew" class="block-3-x params-list">
                    <form action="/api/shop/{{ current_shop.pk }}/yml/add/" method="POST" id="client-pricelist-detail-form" class="form-block edit">
                        <a href="#" id="pricelist-edit-btn"></a>
                        <header>Параметры</header>
                        <label class="pure-g field-wrapper">
                            <div class="pure-u-1-3 field-name">Название YML-файла</div>
                            <div class="pure-u-2-3 field-value">
                                <input name="name" type="text" class="b_input_text" value="">
                            </div>
                        </label>
                        <label class="pure-g field-wrapper">
                            <div class="pure-u-1-3 field-name">Ссылка на YML-файл</div>
                            <div class="pure-u-2-3 field-value">
                                <input name="yml_url" type="text" class="b_input_text" value="">
                            </div>
                        </label>
                        <label class="pure-g field-wrapper">
                            <div class="pure-u-1-3 field-name">География</div>
                            <div class="pure-u-2-3 field-value">
                                <div class="select">
                                    <select name="region">
                                        <option></option>
                                        {% for city in cities %}
                                            <option value="{{ city.id }}">{{ city.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <div class="overlay"></div>
                                    <div class="select-wrapper">
                                        <a href="#" class="current-value b_input_text"></a>
                                        <ul>
                                            {% for city in cities %}
                                                <li><a href="#" data-value="{{ city.id }}" class="choice">{{ city.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </label>
                        <footer>
                            <button type="submit" class="btn btn-purple">Создать</button>
                        </footer>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/apps/client/pricelist/detail.html
{% extends 'client_base.html' %}

{% block content%}
    <div id="client-pricelist-detail">
        <div class="h1">Прайс-лист "<span id="price-list-name">{{ object.name }}</span>"</div>
        <div class="pure-g">
            <div class="pure-u-3-4">
                <div id="client-pricelist-detail-params-form-vew" class="block-3-x params-list">
                    <form method="put" action="{% url 'shop-api:yml-update' object.pk %}" id="client-pricelist-detail-form" class="form-block">
                        <a href="#" id="pricelist-edit-btn"></a>
                        <header>Параметры</header>
                        <label class="pure-g field-wrapper">
                            <div class="pure-u-1-4 field-name">Название YML-файла</div>
                            <div class="pure-u-3-4 field-value">
                                <input name="name" type="text" class="b_input_text" disabled="disabled" value="{{ object.name }}">
                            </div>
                        </label>
                        <label class="pure-g field-wrapper no-edit">
                            <div class="pure-u-1-4 field-name">Ссылка на YML-файл</div>
                            <div class="pure-u-3-4 field-value">{{ object.yml_url }}</div>
                        </label>
                        <label class="pure-g field-wrapper">
                            <div class="pure-u-1-4 field-name">География</div>
                            <div class="pure-u-3-4 field-value">
                                <div class="select disabled">
                                    <select name="region">
                                        <option></option>
                                        {% for city in cities %}
                                            <option value="{{ city.id }}" {% if city.id == object.region.id %}selected{% endif %}>{{ city.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <div class="overlay"></div>
                                    <div class="select-wrapper">
                                        <a href="#" class="current-value b_input_text">{{ object.region.name|default:'' }}</a>
                                        <ul>
                                            {% for city in cities %}
                                                <li><a href="#" data-value="{{ city.id }}" class="choice">{{ city.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </label>
                        <footer>
                            <button type="submit" class="btn btn-purple">Сохранить</button>
                        </footer>
                    </form>
                </div>
            </div>
            <div id="client-pricelist-detail-info-view" class="pure-u-1-4 info-wrapper">
                <div class="pure-g">
                    <div class="pure-u-1-1">Статус:
                        {% if user.client_profile.is_active == 1 %}
                            <span class="status active">активный</span>
                        {% else %}
                            <span class="status inactive">неактивный</span>
                        {% endif %}
                    </div>
                </div>
                <div class="pure-g">
                    <div class="pure-u-2-3">Опубликовать</div>
                    <div class="pure-u-1-3">
                        <label class="switcher-wrapper {% if object.is_published %}on{% endif %}">
                            <input type="checkbox" value="" {% if object.is_published %}checked="checked"{% endif %} />
                            <div class="switcher"></div>
                        </label>
                    </div>
                </div>
                <div class="pure-g">
                    <div class="pure-u-1-1"><a href="#" id="client-pricelist-remove" data-url="{% url 'shop-api:yml-delete' object.pk %}">Удалить прайс-лист</a></div>
                </div>
            </div>
            <div id="client-pricelist-detail-managment-view" class="pure-u-1-1 management-wrapper">
                <div class="block-ful-x">
                    <header>Управление ставками</header>
                    <div id="client-pricelist-detail-categories-view"></div>
                    <footer>
                        <a href="{% url 'client:statistics_pricelist' object.pk %}" class="statistic-link">Посмотреть статистику</a>
                    </footer>
                </div>
            </div>
            <div id="" class="pure-u-1-1 products-wrapper">
                <div class="block-ful-x">
                    <header>Список товаров</header>
                    <div id="client-pricelist-detail-products-view"></div>
                    <footer id="client-pricelist-detail-products-pager-view"></footer>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}