src/apps/alterprice/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from alterprice import views


urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),

    # APPs
    url(r'^markup/', include('markup.urls', namespace="markup")),
    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^catalog/', include('catalog.urls', namespace="catalog")),
    url(r'^client/', include('client.urls', namespace="client")),


    # API urls
    url(r'^api/product/', include('product.api.urls', namespace="product-api")),
    url(r'^api/catalog/', include('catalog.api.urls', namespace="catalog-api")),
    url(r'^api/brand/', include('brand.api.urls', namespace="brand-api")),
    url(r'^api/shop/', include('shop.api.urls', namespace="shop-api")),
    url(r'^api/user/', include('apuser.api.urls', namespace="user-api")),
    url(r'^api/client/', include('client.api.urls', namespace="client-api")),

    # Aadmin urls
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/apps/client/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from client.api import views

urlpatterns = patterns(
    '',
    url(r'^signin/$', views.SignInAPIView.as_view(), name='signin'),
    url(r'^signin/welcome/$', views.SignInAPIView.as_view(), name='signin_welcome'),
    url(r'^signup/$', views.SignUpAPIView.as_view(), name='signup'),
    url(r'^profile/$', views.Profile.as_view(), name='profile'),
    url(r'^profile/password/$', views.ProfilePassword.as_view(), name='profile-password'),
    url(r'^recovery/$', views.Recovery.as_view(), name='recovery'),
    url(r'^recovery/password/$', views.RecoveryPassword.as_view(), name='recovery-password'),
    url(r'^email/update/$', views.UpdateEmail.as_view(), name='email-update'),
    url(r'^invoice/add/$', views.InvoiceCreateView.as_view(), name='invoice-add'),
    url(r'^invoice/list/$', views.InvoiceListView.as_view(), name='invoice-list'),
    url(r'^robokassa/add/$', views.RobokassaCreatePaymentAPIView.as_view(), name='robokassa-add'),
    url(r'^robokassa/result/$', views.RobokassaResultAPIView.as_view(), name='robokassa-result'),
    url(r'^market/offer/$', views.RobokassaResultAPIView.as_view(), name='robokassa-result'),
)

src/apps/client/urls.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, url
from client import views


urlpatterns = patterns(
    '',
    url(r'^$', views.ClientIndexPageView.as_view(), name='index'),
    url(r'^agreements/$', views.ClientAgreementsPageView.as_view(), name='agreements'),
    url(r'^contacts/$', views.ClientContactsPageView.as_view(), name='contacts'),
    # auth urls
    url(r'^login/$', views.ClientSignInPageView.as_view(), name='login'),
    url(r'^signout/$',
        'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('client:index'), },
        name='signout'),
    url(r'^registration/$', views.ClientSignUpPageView.as_view(), name='registration'),
    url(r'^password_reset/$', views.ClientPasswordResetPageView.as_view(), name='password_reset'),

    url(r'^activate/(?P<token>%s)/$' % settings.EMAIL_TOKEN_PATTERN,
        views.ActivateView.as_view(),
        name='activate-link'),
    url(r'^password/(?P<token>%s)/$' % settings.RECOVERY_TOKEN_PATTERN,
        views.RecoveryPassword.as_view(),
        name="recovery-link"),

    # cabinet urls
    url(r'^profile/$', views.ClientProfilePageView.as_view(), name='profile'),
    url(r'^shop/add/$', views.ClientShopAddPageView.as_view(), name='shop_add'),
    url(r'^shop/(?P<pk>\d+)/$', views.ClientShopDetailPageView.as_view(), name='shop_detail'),
    url(r'^wallet/balance/$', views.ClientWalletBalancePageView.as_view(), name='wallet_balance'),
    url(r'^wallet/refill/$', views.ClientWalletRefillPageView.as_view(), name='wallet_refill'),

    url(r'^statistics/shop/(?P<pk>\d+)/$',
        views.ClientStatisticShopView.as_view(),
        name='statistics_shop'),

    url(r'^statistics/pricelist/(?P<pk>\d+)/$',
        views.ClientStatisticPricelistView.as_view(),
        name='statistics_pricelist'
    ),

    url(r'^pricelist/(?P<pk>\d+)/$', views.ClientPricelistDetailPageView.as_view(), name='pricelist_detail'),
    url(r'^pricelist/add/$', views.ClientPricelistAddPageView.as_view(), name='pricelist_add'),
    url(r'^invoice/download/(?P<pk>\d+)/$', views.download_invoice, name='invoice_download'),

    # Middleware UL
    url(r'^shop/change/$', views.ChnageShop.as_view(), name='change-shop'),
)

src/apps/client/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
# PRoject imports
from shop.models.shop import Shop


class ChangeShopForm(forms.Form):
    shop = forms.ModelChoiceField(
        empty_label=_('Выберете магазин'),
        queryset=Shop.objects.all())

src/apps/client/api/views.py
import logging
from hashlib import md5
from urllib.request import urlopen
from math import ceil

from rest_framework import permissions
from rest_framework import status
from rest_framework.renderers import StaticHTMLRenderer
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView, UpdateAPIView, ListCreateAPIView, \
    ListAPIView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth import login as auth_login
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.hashers import make_password
from django.core.urlresolvers import resolve

from apuser.models import BalanceHistory
from apuser.models.payment import InvoiceRequest, Payment
from apuser import models
from apuser.models.profile import EmailDelivery, OperatorProfile
from catalog.models.token import PasswordRecovery
from client.api import serializers
from django.conf import settings
from utils.views import APIView
from django.contrib.auth import update_session_auth_hash


logger = logging.getLogger(__name__)


class SignInAPIView(APIView):
    serializer_class = serializers.SignInSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        auth_login(request, serializer.object)

    def success_data(self, serializer):
        response = {}

        if resolve(self.request.path_info).url_name is 'signin_welcome':
            response['redirect_to'] = reverse_lazy('client:shop_add')
        else:
            response['redirect_to'] = reverse_lazy('client:profile')

        return response


class SignUpAPIView(CreateAPIView):
    serializer_class = serializers.SignUpSerializer
    permission_classes = (
        permissions.AllowAny,
    )

    def perform_create(self, serializer):
        user = serializer.save()
        return user

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        response = {}
        if serializer.is_valid():
            user = self.perform_create(serializer)
            headers = self.get_success_headers(serializer.data)
            response['status'] = 'success'
            response['message'] = _('Для завершения регистрации перейдите по ссылке из письма отправленного на ваш e-mail. Если не найдете во входящих, проверьте "спам"')
            EmailDelivery.objects.make(
                template='client/register.html',
                email=serializer.validated_data.get('email'),
                context={
                    'link': reverse('client:activate-link',
                                    kwargs={'token': user.emailvalidation_set.all()[0].token}),
                    'domain': settings.DEFAULT_HOST
                }

            )
            if user.client_profile.operator:
                operator_email = user.client_profile.operator.user.email
            else:
                emails = [x.user.email for x in OperatorProfile.objects.all()]
                operator_email = ','.join(emails)
            EmailDelivery.objects.make(
                template='operator/register.html',
                email=operator_email
            )
            return Response(response, status=status.HTTP_201_CREATED, headers=headers)
        else:
            response['status'] = 'fail'
            response['errors'] = serializer.errors
            headers = self.get_success_headers(serializer.data)
            return Response(response,
                            status=status.HTTP_400_BAD_REQUEST,
                            headers=headers)


class Recovery(APIView):
    serializer_class = serializers.RecoverySerializer
    permission_classes = (
        permissions.AllowAny,
    )

    def success_action(self, request, serializer):
        email = serializer.validated_data.get('email')
        user = models.AlterPriceUser.objects.get(email=email)
        r = PasswordRecovery.objects.make(user=user)
        EmailDelivery.objects.make(
            template='client/activate.html',
            email=user.email,
            context={'token': r.token}
        )

    def success_data(self, serializer):
        response = {}
        # email = serializer.validated_data.get('email')
        response['message'] = _(
            'Выслано сообщение со ссылкой на восстановление')
        return response


class RecoveryPassword(APIView):
    serializer_class = serializers.RecoveryPasswordSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        password = serializer.validated_data.get('password')
        pr = PasswordRecovery.objects.get_valid(
            token=serializer.validated_data.get('token'))
        pr.recover()
        user = pr.user
        user.set_password(password)
        user.save()

    def success_data(self, serializers):
        response = {}
        response['message'] = _('Ваш пароль был успешно изменен.')
        response['redirect_to'] = reverse('client:login')
        return response


class UpdateEmail(APIView):
    serializer_class = serializers.UpdateEmailSerializer
    permission_classes = (permissions.AllowAny, )

    def success_action(self, request, serializer):
        self.request.user.email = serializer.validated_data.get('new_email')
        self.request.user.save()

    def success_data(self, serializers):
        response = {}
        response['message'] = _('Ваш email был успешно изменен.')
        response['status'] = 'success'
        return response


class InvoiceListView(ListAPIView):
    model = InvoiceRequest
    serializer_class = serializers.InvoiceRequestListSerializer
    permission_classes = (permissions.IsAuthenticated, )

    def get_queryset(self):
        queryset = self.model.objects.filter(client=self.request.user.client_profile)
        return queryset


class InvoiceCreateView(CreateAPIView):
    serializer_class = serializers.InvoiceRequestAddSerializer
    permission_classes = (permissions.IsAuthenticated, )
    model = InvoiceRequest

    def get_queryset(self):
        return self.model.objects.filter(client=self.request.user.client_profile)

    def perform_create(self, serializer):
        ir = serializer.save()
        ir.client = self.request.user.client_profile
        ir.save()

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        response = {}
        if serializer.is_valid():
            self.perform_create(serializer)
            headers = self.get_success_headers(serializer.data)
            response['status'] = 'success'
            response['message'] = _('Запрос на счет отправлен.')
            return Response(response, status=status.HTTP_201_CREATED, headers=headers)
        else:
            response['status'] = 'fail'
            response['errors'] = serializer.errors
            headers = self.get_success_headers(serializer.data)
            return Response(response,
                            status=status.HTTP_400_BAD_REQUEST,
                            headers=headers)


class Profile(APIView):
    serializer_class = serializers.ProfileSerializer

    def success_action(self, request, serializer):
        phone = serializer.validated_data.get('phone')
        request.user.client_profile.phone = phone
        request.user.client_profile.save()

    def success_data(self, serializers):
        response = {}
        response['status'] = 'success'
        return response


class ProfilePassword(APIView):
    serializer_class = serializers.ProfilePasswordSerializer

    def success_action(self, request, serializer):
        password = serializer.validated_data.get('password')
        request.user.set_password(password)
        request.user.save()
        update_session_auth_hash(request, request.user)

    def success_data(self, serializers):
        response = {}
        response['status'] = 'success'
        response['message'] = _('Ваш пароль успешно изменен')
        return response


class RobokassaResultAPIView(APIView):
    serializer_class = serializers.RobokassaResultSerializer
    renderer_classes = (StaticHTMLRenderer, )

    def post(self, request, *args, **kwargs):
        data = self.prepare_data(request)
        serializer = self.serializer_class(data=data, context=dict(request=request))
        response = ''
        if serializer.is_valid():
            payment_id = serializer.validated_data.get('InvId')
            payment = Payment.objects.get(id=payment_id)
            payment.robokassa_success = True
            payment.save()
            BalanceHistory.objects.increase(
                balance=payment.client.balance,
                payment=payment,
            )
            EmailDelivery.objects.make(
                template='client/payment_success.html',
                email=payment.client.user.email,
                context={'amount': payment.amount}
            )
            if payment.client.operator:
                EmailDelivery.objects.make(
                    template='client/payment_success.html',
                    email=payment.client.operator.user.email,
                    context={'amount': payment.amount}
                )
            self.success_action(request, serializer)
            response = 'OK%d' % payment_id
        return Response(response, status=200)


class RobokassaCreatePaymentAPIView(CreateAPIView):
    model = Payment
    permission_classes = (permissions.IsAuthenticated, )
    serializer_class = serializers.RobokassaCreateSerializer

    def perform_create(self, serializer):
        # payment = serializer.save()
        payment = self.model(
            client=self.request.user.client_profile,
            amount=serializer.validated_data.get('OutSum'),
            payment_type=Payment.ONLINE,
            payment_detail=Payment.PAYMENT,
        )
        payment.save()
        return payment

src/templates/apps/client/index.html
{% extends 'base_empty.html' %}

{% block content%}
    <div id="client-index-page">
        <img src="{{ STATIC_URL }}dist/images/logo-big.svg">
        <div class="h1">Ваши товары для пользователей по всей России</div>
        <p>Если у вашего магазина есть свой сайт, вы можете добавить на Маркетплейс и свои предложения.</p>
        <p>Платите только за клики пользователя по вашему товарному предложению. Минимальная стоимость клика составляет 3 рубля (1,5 рубля для книг). Эта схема позволяет управлять ценой клика и выводить свои товары на более заметные места.</p>
        <div class="pure-g links-wrapper">
            <div class="pure-u-1-2">
                <a href="{% url 'client:registration' %}" class="btn btn-yellow btn-full-width shadow">Регистрация</a>
            </div>
            <div class="pure-u-1-2">
                <a href="{% url 'client:login' %}" class="btn btn-purple btn-full-width shadow">Вход</a>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/apps/client/login.html
{% extends 'base_empty.html' %}

{% block content%}
    <div id="sign-in-page">
        <a href="{% url 'client:index' %}"><img src="{{ STATIC_URL }}dist/images/logo-black.svg"></a>
        <div class="h1">Вход</div>
        {% if welcome %}
            <p class="welcome">Поздравляем с успешной регистрацией! Авторизируйтесь для дальнейшей работы.</p>
        {% endif %}
        <div id="client-login-form-view">
            {% if welcome %}
                <form action="{% url 'client-api:signin_welcome' %}" method="POST" id="login-form" class="form-block">
            {% else %}
                <form action="{% url 'client-api:signin' %}" method="POST" id="login-form" class="form-block">
            {% endif %}
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Email</div>
                    <div class="pure-u-1-1 field-value">
                        <input type="text" name="email" class="b_input_text focus_grey shadow" value="">
                    </div>
                </label>
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Пароль</div>
                    <div class="pure-u-1-1 field-value">
                        <input type="password" name="password" class="b_input_text focus_grey shadow" value="">
                    </div>
                </label>
                <div class="pure-g form-footer">
                    <div class="pure-u-1-2">
                        <a href="{% url 'client:password_reset' %}" class="btn btn-link btn-link-purple">Забыли пароль?</a>
                    </div>
                    <div class="pure-u-1-2 submit-wrapper">
                        <button type="submit" class="btn btn-purple btn-full-width shadow">Войти</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

src/templates/apps/client/password_reset.html
{% extends 'base_empty.html' %}

{% block content %}
    <div id="sign-in-page">
        <a href="{% url 'client:index' %}"><img src="{{ STATIC_URL }}dist/images/logo-black.svg"></a>
        <div class="h1">Запрос на восстановление пароля</div>
        <form action="{% url 'client-api:recovery' %}" id="client-password-reset-form-view" method="POST" class="form-block">
            <label class="pure-g field-wrapper vertical-field">
                <div class="pure-u-1-1 field-name">Email</div>
                <div class="pure-u-1-1 field-value">
                    <input name="email" type="text" class="b_input_text focus_grey shadow" value="">
                </div>
            </label>
            <div class="pure-g form-footer">
                <div class="pure-u-1-2">
                    <a href="{% url 'client:login' %}" class="btn btn-link btn-link-purple">Вернуться к форме входа</a>
                </div>
                <div class="pure-u-1-2 submit-wrapper">
                    <button type="submit" class="btn btn-purple btn-full-width shadow">ОТПРАВИТЬ</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/apps/client/profile.html
{% extends 'client_base.html' %}

{% block content%}
    <div id="client-profile-page">
        <div class="h1">Профиль</div>
        <div class="block-ful-x">
            <div class="pure-g">
                <div class="pure-u-1-2">
                    <div id="client-profile-form-view">
                        <form method="post" action="{% url 'client-api:profile' %}" id="edit-profile-form" class="form-block">
                            <a href="#" id="profile-edit-btn"></a>
                            <div class="name">
                                <span>{{ user.get_short_name }}</span>
                                <div class="status ok">
                                    <div class="tooltip">Профиль подтвержден</div>
                                </div>
                            </div>
                            <label class="pure-g field-wrapper no-edit">
                                <div class="pure-u-2-5 field-name">Email</div>
                                <div class="pure-u-3-5 field-value email-field">{{ user.email }}</div>
                            </label>
                            <label class="pure-g field-wrapper">
                                <div class="pure-u-2-5 field-name">Телефон</div>
                                <div class="pure-u-3-5 field-value">
                                    <input name="phone" type="text" class="b_input_text phone-mask" disabled="disabled" value="{{ user.client_profile.phone }}" />
                                </div>
                            </label>
                            <div class="pure-g field-wrapper no-edit">
                                <div class="pure-u-2-5 field-name">Страна</div>
                                <div class="pure-u-3-5 field-value">Россия</div>
                            </div>
                            <div class="pure-g field-wrapper no-edit">
                                <div class="pure-u-2-5 field-name">Регион</div>
                                <div class="pure-u-3-5 field-value">Александровский</div>
                            </div>
                            <div class="pure-g field-wrapper no-edit">
                                <div class="pure-u-2-5 field-name">Форма организации</div>
                                <div class="pure-u-3-5 field-value">Юридическое лицо</div>
                            </div>
                            <div class="pure-g field-wrapper no-edit">
                                <div class="pure-u-2-5 field-name">Название компании</div>
                                <div class="pure-u-3-5 field-value">{{ user.client_profile.org_name }}</div>
                            </div>
                            <footer>
                                <button type="submit" class="btn btn-purple">Сохранить</button>
                            </footer>
                        </form>
                    </div>
                </div>
                <div class="pure-u-1-2 text-right">
                    {% include 'blocks/client/call_center.html' %}
                </div>
            </div>
        </div>
        <div class="pure-g">
            <div class="pure-u-1-2">
                <div class="block-2-x">
                    <header>Смена пароля</header>
                    <div id="client-profile-password-form-view">
                        <form method="post" action="{% url 'client-api:profile-password' %}" id="client-profile-password-form" class="form-block">
                            <label class="pure-g field-wrapper">
                                <div class="pure-u-2-5 field-name">Текущий пароль</div>
                                <div class="pure-u-3-5 field-value">
                                    <input name="old_password" type="password" class="b_input_text" value="" />
                                </div>
                            </label>
                            <label class="pure-g field-wrapper">
                                <div class="pure-u-2-5 field-name">Новый пароль</div>
                                <div class="pure-u-3-5 field-value">
                                    <input name="password" type="password" class="b_input_text" value="" />
                                </div>
                            </label>
                            <label class="pure-g field-wrapper">
                                <div class="pure-u-2-5 field-name">Повторите пароль</div>
                                <div class="pure-u-3-5 field-value">
                                    <input name="confirm_password" type="password" class="b_input_text" value="" />
                                </div>
                            </label>
                            <footer>
                                <button type="submit" class="btn btn-purple">Сменить пароль</button>
                            </footer>
                        </form>
                    </div>
                </div>
            </div>
            <div class="pure-u-1-2 text-right">
                <div class="block-2-x text-left">
                    <header>Смена email</header>
                    <div id="client-profile-email-form-view">
                        <form action="{% url 'client-api:email-update' %}" method="post" class="form-block">
                            <label class="pure-g field-wrapper">
                                <div class="pure-u-2-5 field-name">Текущий Email</div>
                                <div class="pure-u-3-5 field-value">
                                    <input type="text" name="email" class="b_input_text" value="" />
                                </div>
                            </label>
                            <label class="pure-g field-wrapper">
                                <div class="pure-u-2-5 field-name">Новый Email</div>
                                <div class="pure-u-3-5 field-value">
                                    <input type="text" name="new_email" class="b_input_text new-email" value="" />
                                </div>
                            </label>
                            <label class="pure-g field-wrapper">
                                <div class="pure-u-2-5 field-name"></div>
                                <div class="pure-u-3-5 field-value"></div>
                            </label>
                            <footer>
                                <button type="submit" class="btn btn-purple">Сменить Email</button>
                            </footer>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/apps/client/registration.html
{% extends 'base_empty.html' %}

{% block content%}
    <div id="sign-up-page">
        <a href="{% url 'client:index' %}"><img src="{{ STATIC_URL }}dist/images/logo-black.svg"></a>
        <div class="h1">Регистрация</div>
        <div id="client-registration-form-view">
            <form action="{% url 'client-api:signup' %}" id="registration-form" class="form-block" method="POST">
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Имя</div>
                    <div class="pure-u-1-1 field-value">
                        <input name="first_name" type="text" class="b_input_text focus_grey shadow" value="">
                    </div>
                </label>
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Фамилия</div>
                    <div class="pure-u-1-1 field-value">
                        <input name="last_name" type="text" class="b_input_text focus_grey shadow" value="">
                    </div>
                </label>
                <div class="pure-g field-wrapper vertical-field radio-wrapper">
                    <div class="pure-u-1-2 field-value">
                        <label class="radio"><input type="radio" checked name="ownership_type" value="1" /> Физическое лицо</label>
                    </div>
                    <div class="pure-u-1-2 field-value">
                        <label class="radio"><input type="radio" name="ownership_type" value="0" /> Юридическое лицо</label>
                    </div>
                </div>
                <div class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Регион России</div>
                    <div class="pure-u-1-1 field-value">
                        <input name="city" type="text" class="b_input_text focus_grey shadow" value="">
                    </div>
                </div>
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Номер телефона</div>
                    <div class="pure-u-1-1 field-value">
                        <input name="phone" type="text" class="phone-mask b_input_text focus_grey shadow" value="">
                    </div>
                </label>
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Компания</div>
                    <div class="pure-u-1-1 field-value">
                        <input name="company" type="text" class="b_input_text focus_grey shadow" value="">
                    </div>
                </label>
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Email</div>
                    <div class="pure-u-1-1 field-value">
                        <input name="email" type="text" class="b_input_text focus_grey shadow" value="">
                    </div>
                </label>
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Пароль</div>
                    <div class="pure-u-1-1 field-value">
                        <input name="password" type="password" class="b_input_text focus_grey shadow" value="">
                    </div>
                </label>
                <label class="pure-g field-wrapper vertical-field">
                    <div class="pure-u-1-1 field-name">Повторите пароль</div>
                    <div class="pure-u-1-1 field-value">
                        <input name="confirm_password" type="password" class="b_input_text shadow focus_grey" value="">
                    </div>
                </label>
                <label class="pure-g field-wrapper vertical-field operator-code">
                    <div class="pure-u-1-1 field-name"><a href="#" class="operator-code-show-link">ВВЕСТИ КОД ОПЕРАТОРА</a></div>
                    <div class="pure-u-1-1 field-value">
                        <input name="operator_code" type="text" class="b_input_text shadow focus_grey" value="">
                    </div>
                </label>
                <div class="pure-g field-wrapper vertical-field checkbox-wrapper">
                    <div class="pure-u-1-1 field-value">
                        <label class="checkbox">
                            <input name="user_agreement" type="checkbox" value="true"> Я согласен с <a href="#">условиями оферты и политикой конфиденциальности</a>
                        </label>
                    </div>
                </div>
                <div class="pure-g form-footer">
                    <div class="pure-u-1-2"></div>
                    <div class="pure-u-1-2 submit-wrapper">
                        <button type="submit" class="btn btn-purple btn-full-width shadow">Зарегестрироваться</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}