src/apps/alterprice/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from alterprice import views


urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),

    # APPs
    url(r'^markup/', include('markup.urls', namespace="markup")),
    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^catalog/', include('catalog.urls', namespace="catalog")),
    url(r'^client/', include('client.urls', namespace="client")),


    # API urls
    url(r'^api/product/', include('product.api.urls', namespace="product-api")),
    url(r'^api/catalog/', include('catalog.api.urls', namespace="catalog-api")),
    url(r'^api/brand/', include('brand.api.urls', namespace="brand-api")),
    url(r'^api/shop/', include('shop.api.urls', namespace="shop-api")),
    url(r'^api/user/', include('apuser.api.urls', namespace="user-api")),
    url(r'^api/client/', include('client.api.urls', namespace="client-api")),

    # Aadmin urls
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/apps/catalog/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from catalog.api import views

urlpatterns = patterns(
    '',
    url(r'^category/list/$', views.CategoryList.as_view(), name='category-list'),
    url(r'^cities/list/$', views.CitiesList.as_view(), name='cities-list'),
)

src/apps/catalog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from catalog import views


urlpatterns = patterns(
    '',
    url(r'^$', views.CatalogAllCategoriesPageView.as_view(), name='categories_list'),
    url(r'^(?P<pk>\d+)/$', views.CatalogCategoriesListPageView.as_view(), name='category_categories_list'),
    url(r'^(?P<pk>\d+)/products/$', views.CatalogCategoryProductListPageView.as_view(), name='category_products_list'),
    url(r'^search/$', views.CatalogSearchProductsPageView.as_view(), name='search_products_list'),
    url(r'statistics/$', views.CategoryStatisticsView.as_view(), name='statistics'),

    url(r'^click/(?P<pk>\d+)/$', views.ClickOffer.as_view(), name='click-offer'),

    # Middleware URL
    url(r'^city/change/$', views.ChangeCity.as_view(), name='change-city'),
)

src/apps/client/urls.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, url
from client import views


urlpatterns = patterns(
    '',
    url(r'^$', views.ClientIndexPageView.as_view(), name='index'),
    url(r'^agreements/$', views.ClientAgreementsPageView.as_view(), name='agreements'),
    url(r'^contacts/$', views.ClientContactsPageView.as_view(), name='contacts'),
    # auth urls
    url(r'^login/$', views.ClientSignInPageView.as_view(), name='login'),
    url(r'^signout/$',
        'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('client:index'), },
        name='signout'),
    url(r'^registration/$', views.ClientSignUpPageView.as_view(), name='registration'),
    url(r'^password_reset/$', views.ClientPasswordResetPageView.as_view(), name='password_reset'),

    url(r'^activate/(?P<token>%s)/$' % settings.EMAIL_TOKEN_PATTERN,
        views.ActivateView.as_view(),
        name='activate-link'),
    url(r'^password/(?P<token>%s)/$' % settings.RECOVERY_TOKEN_PATTERN,
        views.RecoveryPassword.as_view(),
        name="recovery-link"),

    # cabinet urls
    url(r'^profile/$', views.ClientProfilePageView.as_view(), name='profile'),
    url(r'^shop/add/$', views.ClientShopAddPageView.as_view(), name='shop_add'),
    url(r'^shop/(?P<pk>\d+)/$', views.ClientShopDetailPageView.as_view(), name='shop_detail'),
    url(r'^wallet/balance/$', views.ClientWalletBalancePageView.as_view(), name='wallet_balance'),
    url(r'^wallet/refill/$', views.ClientWalletRefillPageView.as_view(), name='wallet_refill'),

    url(r'^statistics/shop/(?P<pk>\d+)/$',
        views.ClientStatisticShopView.as_view(),
        name='statistics_shop'),

    url(r'^statistics/pricelist/(?P<pk>\d+)/$',
        views.ClientStatisticPricelistView.as_view(),
        name='statistics_pricelist'
    ),

    url(r'^pricelist/(?P<pk>\d+)/$', views.ClientPricelistDetailPageView.as_view(), name='pricelist_detail'),
    url(r'^pricelist/add/$', views.ClientPricelistAddPageView.as_view(), name='pricelist_add'),
    url(r'^invoice/download/(?P<pk>\d+)/$', views.download_invoice, name='invoice_download'),

    # Middleware UL
    url(r'^shop/change/$', views.ChnageShop.as_view(), name='change-shop'),
)

src/apps/catalog/models/category.py
import os
from django.db import models
from django.db.models import query
from django.utils.translation import ugettext_lazy as _
from marketapi.api import MarketAPI
from utils.abstract_models import NameModel, YMkey
from easy_thumbnails.fields import ThumbnailerField


class CategoryQuerySet(query.QuerySet):
    def by_ymid(self, ym_id):
        return self.filter(ym_id=ym_id)


class CategoryManager(models.Manager):
    def get_list(self):
        return self.all()

    def get_frist_level(self):
        qs = self.filter(parent__isnull=True)
        return qs.prefetch_related('children')

    def get_or_create(self, ym_id):
        try:
            return self.get(ym_id=ym_id)
        except self.model.DoesNotExist:
            return self.fetch_make(ym_id=ym_id)

    def fetch_make(self, ym_id):
        ym_category = MarketAPI.get_category(ym_id)['category']

        if 'parentId' in ym_category \
                and ym_category['parentId'] != 0 \
                and ym_category['parentId'] != 90401:
            parent = self.get_or_create(ym_category['parentId'])
            depth = parent.depth + 1
        else:
            depth = 0
            parent = None

        return self.create(
            name=ym_category['uniqName'],
            ym_id=ym_id,
            parent=parent,
            depth=depth,
        )

    def make(self, name, ym_id, parent=None):
        obj = self.model()
        obj.name = name
        obj.ym_id = ym_id
        obj.parent = parent
        obj.save()
        return obj



def get_photo_path(instance, filename):
    return os.path.join("category/", filename)


class Category(NameModel, YMkey):
    MAX_DEPTH_LEVEL = 4

    parent = models.ForeignKey("self",
                               blank=True,
                               null=True,
                               related_name="children")
    click_count = models.IntegerField(default=0,
                                      verbose_name=_('Количество кликов'))
    shop_count = models.IntegerField(default=0,
                                     verbose_name=_('Количество магазинов'))
    goods_count = models.IntegerField(default=0,
                                      verbose_name=_('Количество товаров'))
    depth = models.IntegerField(default=0,
                                verbose_name=_('Глубина наследования'))
    photo = ThumbnailerField(blank=True,
                             null=True,
                             default=None,
                             upload_to=get_photo_path,
                             verbose_name=_('Фото'))
    full_path = models.CharField(max_length=200, blank=True, null=True)
    cached_product_photo = models.CharField(blank=True,
                                            null=True,
                                            default=None,
                                            max_length=255,
                                            verbose_name=_('Временное фото'))

    objects = CategoryManager.from_queryset(CategoryQuerySet)()

    def _get_thumbnail(self):
        if self.photo:
            try:
                return self.photo.url
            except AttributeError:
                pass

        return None


    def get_preview(self):
        '''
        Возвращает изображение категории или изображение
        рандомного товара одной из подкатегорий
        '''

        if self.depth == self.MAX_DEPTH_LEVEL:
            return None

        thumbnail = self._get_thumbnail()

        if thumbnail:
            url = thumbnail
        elif self.cached_product_photo:
            url = self.cached_product_photo
        else:
            category = self
            parents = [self]
            depth = self.depth
            url = None

            # если у текущей категории нет продуктов, проходимся по подкатегориям
            # пока не найдем категорию у которой есть продукты или не упрёмся
            # в самую нижнюю категорию
            while depth <= self.MAX_DEPTH_LEVEL:
                nonempty_category = Category.objects.filter(parent__in=parents)\
                                                    .filter(product__isnull=False)\
                                                    .order_by('?').first()
                if nonempty_category:
                    category = nonempty_category
                    break

                parents = Category.objects.filter(parent__in=parents)
                depth += 1

            try:
                # проходим по всем фото всех категорий пока не получим урл фото
                for product in category.product_set.order_by('?'):
                    if product.productphoto_set.all():
                        for photo in product.productphoto_set.order_by('?'):
                            if photo.photo.url:
                                url = photo.photo.url
                                self.cached_product_photo = url
                                self.save()
                    else:
                        continue

            except AttributeError:
                pass

        return url


    def get_children(self):
        return Category.objects.filter(parent=self.pk)

    def get_url(self):
        return "/catalog/%d/" % self.pk

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Категория')
        verbose_name_plural = _('Категории')

src/apps/catalog/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from catalog.models.city import City


class ChangeCityForm(forms.Form):
    city = forms.ModelChoiceField(
        empty_label=_('Выберете город'),
        queryset=City.objects.all())

src/apps/catalog/api/views.py
from rest_framework.generics import ListAPIView
# Project imports
from catalog import models
from catalog.api import serializers
from catalog.models.category import Category
from catalog.models.city import City


class CategoryList(ListAPIView):
    serializer_class = serializers.CategorySerializer
    model = Category

    def get_queryset(self):
        return self.model.objects.get_frist_level()


class CitiesList(ListAPIView):
    serializer_class = serializers.CitySerializer
    model = City

src/apps/catalog/views.py
from django.db.models import Q
from django.http import Http404
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView, FormView, RedirectView
from django.views.generic.detail import DetailView
from datetime import datetime, date
# Project imports
from catalog.forms import ChangeCityForm
from brand.models import Brand
from catalog.models.category import Category
from catalog.models.city import City
from product.models import Offer
from apuser.models import Click, Balance, BalanceHistory
from catalog.models.statistics import CategoryStatistics
from shop.models.shop import Shop


class CatalogAllCategoriesPageView(TemplateView):
    template_name = "apps/catalog/main.html"

    def get_context_data(self, **kwargs):
        context = super(CatalogAllCategoriesPageView, self).get_context_data(**kwargs)
        return context


class CatalogCategoriesListPageView(DetailView):
    model = Category

    def get_template_names(self):
        if self.object.depth == 1:
            return "apps/catalog/subcategories_list.html"
        return "apps/catalog/categories_list.html"

    def get_context_data(self, **kwargs):
        context = super(CatalogCategoriesListPageView, self).get_context_data(**kwargs)
        context['children_categories'] = self.object.get_children()
        if self.object.parent:
            context['parent_category'] = self.object.parent.pk
        return context


class CatalogCategoryProductListPageView(DetailView):
    model = Category

    template_name = "apps/catalog/category_products_list.html"

    def get_context_data(self, **kwargs):
        context = super(CatalogCategoryProductListPageView, self).get_context_data(**kwargs)
        context['current_app'] = 'catalog-items-list'
        context['brands'] = Brand.objects.filter(
            Q(product__category=self.object) |
            Q(product__category__parent=self.object) |
            Q(product__category__parent__parent=self.object) |
            Q(product__category__parent__parent__parent=self.object)
        ).distinct()
        if self.object.parent:
            context['parent_category'] = self.object.parent.pk
        context['children_categories'] = self.object.get_children()
        return context


class CatalogSearchProductsPageView(TemplateView):
    template_name = "apps/catalog/search_products_list.html"

    def get_context_data(self, **kwargs):
        context = super(CatalogSearchProductsPageView, self).get_context_data(**kwargs)
        context['current_app'] = 'catalog-search'
        context['search'] = self.request.GET.get('search', '')
        return context


class ChangeCity(FormView):
    form_class = ChangeCityForm
    template_name = 'change_city_form.html'

    def get_success_url(self):
        return reverse('catalog:categories_list')

    def get_initials(self):
        return {'': City.objects.filter(user=self.request.user)}

    def form_valid(self, form):
        city = form.cleaned_data.get('city')
        self.request.session['city_id'] = city.id
        return super(ChangeCity, self).form_valid(form)


class ClickOffer(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        offer_id = kwargs.get('pk', None)

        try:
            offer = Offer.objects.get(id=offer_id)
        except Offer.DoesNotExist:
            raise Http404

        click = Click.objects.make(offer=offer,
                                   user_ip=self.request.META.get('REMOTE_ADDR'))
        user = offer.shop.user

        try:
            balance = user.client_profile.balance
        except:
            balance = Balance.objects.make(client=user.client_profile)

        BalanceHistory.objects.decrease(
            balance=balance,
            click=click,
            value=offer.click_price)

        return offer.url


class CategoryStatisticsView(TemplateView):
    template_name = "apps/catalog/category_statistics.html"

    def extract_get_args(self):
        date_from = self.request.GET.get('date_from', None)
        date_to = self.request.GET.get('date_to', None)

        date_from = datetime.strptime(date_from, '%d.%m.%y').date() if date_from else None
        date_to = datetime.strptime(date_to, '%d.%m.%y').date() if date_to else date.today()

        if not date_from:
            date_from = CategoryStatistics.objects.all().order_by('created').first().created

        return date_from, date_to

    def get_category_list(self):
        search = self.request.GET.get('search', None)
        category_list = Category.objects.all()

        if search:
            category_list = category_list.filter(name__icontains=search)

        return category_list

    def get_context_data(self, **kwargs):
        context = super(CategoryStatisticsView, self).get_context_data()
        date_from, date_to = self.extract_get_args()
        category_list = self.get_category_list()

        object_list = list()
        for category in category_list:
            try:
                start_statistics = CategoryStatistics.objects.get(created=date_from,
                                                                  category=category)
                end_statistics = CategoryStatistics.objects.get(created=date_to,
                                                                category=category)
            except CategoryStatistics.DoesNotExist:
                continue

            shop_list = Shop.objects.filter(offer__product__category=category).distinct()

            object_list.append({
                "name": start_statistics.category.name,
                "level": start_statistics.category.depth,
                "click_count": end_statistics.click_count - start_statistics.click_count,
                "product_count": end_statistics.product_count - start_statistics.product_count,
                "shop_count": end_statistics.shop_count - start_statistics.shop_count,
                "shop_list": shop_list
            })

        context["object_list"] = object_list
        return context

src/templates/apps/catalog/categories_list.html
{% extends 'base.html' %}

{% load catalog_utils %}

{% block content%}
    <div id="subcategories-list-page">
        <div id="block-breadcrumbs">
            <ul>
                <li><a href="{% url 'catalog:categories_list' %}">Все категории</a></li>
                {% for item in object|get_breadcrumbs_by_category %}
                    {% if forloop.last %}
                        <li><span>{{ item.object.name }}</span></li>
                    {% else %}
                        <li><a href="{{ item.url }}">{{ item.object.name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="h1">{{ object.name }}</div>
        <div>
            {% for category in children_categories %}
                {% cycle '<div class="row">' '' '' %}
                <div class="block-03-x">
                    <a href="{% url 'catalog:category_categories_list' category.pk %}">
                        <div class="image" {% if category.get_preview %}style="background-image: url({{ category.get_preview }})"{% endif %}></div>
                        <div class="title">{{ category.name }}</div>
                    </a>
                    <ul>
                        {% for subcategory in category.get_children %}
                            <li><a href="{% url 'catalog:category_products_list' subcategory.id %}">{{ subcategory.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% if forloop.last %}
                    </div>
                {% else %}
                    {% cycle '' '' '</div>' %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

src/templates/apps/catalog/category_products_list.html
{% extends 'base.html' %}

{% load catalog_utils %}

{% block content%}
    <div id="items-list-page">
        <div id="block-breadcrumbs">
            <ul>
                <li><a href="{% url 'catalog:categories_list' %}">Все категории</a></li>
                {% for item in object|get_breadcrumbs_by_category %}
                    {% if forloop.last %}
                        <li><span>{{ item.object.name }}</span></li>
                    {% else %}
                        <li><a href="{{ item.url }}">{{ item.object.name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="h1">{{ object.name }}</div>
        <div class="pure-g">
            <div class="pure-u-3-4">
                {% if children_categories|length > 0 %}
                    <div class="categories-filter-wrapper">
                        <div class="categories-filter">
                            {% for category in children_categories %}
                                <a href="{% url 'catalog:category_products_list' category.pk %}" class="btn btn-sea">{{ category.name }}</a>
                            {% endfor %}
                        </div>
                        <a href="#" class="show-all" style="display: none;">Все {{ children_categories|length }} категорий</a>
                    </div>
                {% endif %}
                <div class="items-list-page-wrapper">
                    <div id="catalog-products-layout">
                        <div id="catalog-products-list-view" class="items-wrapper"></div>
                    </div>
                    <div id="catalog-products-pager-view">
                        <button type="button" class="btn btn-grey btn-full-width" style="display: none;">Показать еще</button>
                    </div>
                    <div id="categories-list-page" class="not-found-products">
                        <p>По вашему запросу ничего не нашлось.</p>
                    </div>
                </div>
            </div>
            <div class="pure-u-1-4 text-right">
                <div class="block-1-x text-left">
                    <div id="catalog-products-filter-view">
                        <form class="items-filter">
                            <input type="hidden" name="category" id="category" value="{{ object.pk }}" />
                            <div class="price">
                                <span class="title">Цена, руб</span>
                                <div class="pure-g">
                                    <div class="pure-u-1-2">
                                        <label>от <input type="text" id="price_from" placeholder="0" /></label>
                                    </div>
                                    <div class="pure-u-1-2">
                                        <label>до <input type="text" id="price_till" placeholder="9999" /></label>
                                    </div>
                                </div>
                            </div>
                            <div class="producers">
                                <span class="title">Производитель</span>
                                {% for brand in brands %}
                                    <label class="checkbox"><input type="checkbox" value="{{ brand.pk }}" class="brand-input" /> {{ brand.name }}</label>
                                {% endfor %}
                            </div>
                            <button class="submit" type="submit">Показать <span>(40)</span></button>
                        </form>
                    </div>
                </div>
                <div id="banner">
                    <a href="http://alterprice.staging.corp.createdigital.me" target="_blank"><img src="/static/dist/images/banner.jpg" /></a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/apps/catalog/category_statistics.html
<form action="{% url 'catalog:statistics' %}" method="get">
    <input type="text" name="search"><br>
    С <input type="text" name="date_from"><br>
    По <input type="text" name="date_to"><br>
    <input type="submit" value="Поиск"><br>
</form>

<br><br>

<table border="1">
    <tr>
        <td>Название</td>
        <td>Уровень</td>
        <td>Клики</td>
        <td>Продукты</td>
        <td>Магазины</td>
    </tr>
    {% for object in object_list %}
        <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.level }}</td>
            <td>{{ object.click_count }}</td>
            <td>{{ object.product_count }}</td>
            <td>{{ object.shop_count }}</td>
        </tr>
        {% for shop in object.shop_list %}
            <tr>
                <td>
                    <a href="{% url 'admin:shop_shop_change' shop.id%}">{{ shop.name }}</a>
                </td>
            </tr>
        {% endfor %}
    {% endfor %}
</table>

src/templates/apps/catalog/main.html
{% extends 'base.html' %}

{% block content%}
    <div id="categories-list-page">
        <div class="h1">Все категории</div>
        <div>
            {% for category in categories  %}
                <a href="{% url 'catalog:category_categories_list' category.pk %}" class="block-1-1">
                    <div class="image" {% if category.get_preview %}style="background-image: url({{ category.get_preview }})"{% endif %}></div>
                    <div class="title">{{ category.name }}</div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

src/templates/apps/catalog/search_products_list.html
{% extends 'base.html' %}

{% block content%}
    <div id="items-list-page">
        <div class="items-list-page-wrapper">
            <div class="found-products">
                <div class="h1">Результаты поиска по запросу - "{{ search }}"</div>
                <div class="pure-g">
                    <div class="pure-u-3-4">
                        <div id="catalog-products-layout-wrapper">
                            <div id="catalog-products-layout">
                                <div class="categories-filter-wrapper">
                                    <div id="catalog-search-categories-list-view-wrapper">

                                    </div>
                                </div>
                                <div id="catalog-products-list-view" class="items-wrapper"></div>
                                <div id="catalog-offers-layout"></div>
                            </div>
                            <div id="catalog-products-pager-view">
                                <button type="button" class="btn btn-grey btn-full-width" style="display: none;">Показать еще</button>
                            </div>
                        </div>
                    </div>
                    <div class="pure-u-1-4 text-right">
                        <div class="block-1-x text-left">
                            <div id="catalog-products-filter-view">
                                <form class="items-filter">
                                    <input type="hidden" name="category" id="category" value="" />
                                    <input type="hidden" name="search" id="search" value="{{ search }}" />
                                    <div class="price" style="border: none; margin-bottom: 0;">
                                        <span class="title">Цена, руб</span>
                                        <div class="pure-g">
                                            <div class="pure-u-1-2">
                                                <label>от <input type="text" id="price_from" placeholder="0" /></label>
                                            </div>
                                            <div class="pure-u-1-2">
                                                <label>до <input type="text" id="price_till" placeholder="9999" /></label>
                                            </div>
                                        </div>
                                    </div>
                                    <button class="submit" type="submit">Показать <span>(40)</span></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="categories-list-page" class="not-found-products">
                <div class="h1">По вашему запросу ничего не нашлось.</div>
                <p>Попробуйте упростить формулировку или воспользуйтесь поиском по категориям.</p>
                <hr>
                <div class="h1">Все категории</div>
                <div>
                    {% for category in categories  %}
                        <a href="{% url 'catalog:category_categories_list' category.pk %}" class="block-1-1">
                            <div class="image" {% if category.get_preview %}style="background-image: url({{ category.get_preview }})"{% endif %}></div>
                            <div class="title">{{ category.name }}</div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

src/templates/apps/catalog/subcategories_list.html
{% extends 'base.html' %}

{% load catalog_utils %}

{% block content%}
    <div id="categories-list-page">
        <div id="block-breadcrumbs">
            <ul>
                <li><a href="{% url 'catalog:categories_list' %}">Все категории</a></li>
                {% for item in object|get_breadcrumbs_by_category %}
                    {% if forloop.last %}
                        <li><span>{{ item.object.name }}</span></li>
                    {% else %}
                        <li><a href="{{ item.url }}">{{ item.object.name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="h1">{{ object.name }}</div>
        <div>
            {% for category in object.get_children  %}
                <a href="{% url 'catalog:category_products_list' category.pk %}" class="block-1-1">
                    <div class="image" {% if category.get_preview %}style="background-image: url({{ category.get_preview }})"{% endif %}></div>
                    <div class="title">{{ category.name }}</div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}